apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  params:
    - name: imageName
      type: string
      description: "The name of the image to build"
      default: "mean-stack-app"
  tasks:
    - name: git-clone-1-13-0
      params:
        - name: url
          value: 'https://github.com/HunterGerlach/mean-stack-app'
        - name: revision
          value: 'nodejs-express' # This is the branch name use during development of this feature
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:697b1d12faa0c3ddde73706b304b3c267539bca689ae614815f2186d6befce0b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone-1-13-0
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: s2i-nodejs-1-13-0
      params:
        - name: VERSION
          value: latest
        - name: PATH_CONTEXT
          value: 02-express-app # This is the directory name use during development of this feature
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.imageName)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:3c2ea396a114221575a4031d90d28c43563f7b96288374e0ba8b22de3ed97b5a
        - name: SKIP_PUSH
          value: 'false'
        - name: ENV_VARS
          value: []
      runAfter:
        - git-clone-1-13-0
      taskRef:
        kind: ClusterTask
        name: s2i-nodejs-1-13-0
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: openshift-deploy-task
      params:
        - name: APP_NAME
          value: $(params.imageName)
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.imageName)
        - name: NAMESPACE
          value: $(context.pipelineRun.namespace)
      runAfter:
        - s2i-nodejs-1-13-0
      taskRef:
        kind: Task
        name: openshift-deploy-task
  workspaces:
    - name: pipeline-workspace
