apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-community-server
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb-community-server
